---
- hosts: localhost
  vars:
    user_product_details:
      product_name: "JBoss"
      product_version: "0.1"

  tasks:
  - name: set_fact
    set_fact:
      product_name: "{{ item.product_name}}"
      product_version: "{{ item.product_version }}"
    with_items:
      - "{{ user_product_details }}"

  - name: test custom module
    anisble_ARTF:
      product_name: "{{ item.product_name}}"
      product_version: "{{ item.product_version }}"
    with_items:
      - "{{ user_product_details }}"
    register: product_details
  
  - debug:
      var: product_details.results.dict['dir_product_name']
  


      